/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdministracaoRouteImport } from './routes/_authenticated/administracao'
import { Route as ApresentacaoMatchIdRouteImport } from './routes/apresentacao.$matchId'
import { Route as RelatorioMatchIdRouteImport } from './routes/relatorio.$matchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdministracaoRoute =
  AuthenticatedAdministracaoRouteImport.update({
    id: '/administracao',
    path: '/administracao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApresentacaoMatchIdRoute = ApresentacaoMatchIdRouteImport.update({
  id: '/apresentacao/$matchId',
  path: '/apresentacao/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioMatchIdRoute = RelatorioMatchIdRouteImport.update({
  id: '/relatorio/$matchId',
  path: '/relatorio/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/apresentacao/$matchId': typeof ApresentacaoMatchIdRoute
  '/relatorio/$matchId': typeof RelatorioMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/apresentacao/$matchId': typeof ApresentacaoMatchIdRoute
  '/relatorio/$matchId': typeof RelatorioMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/administracao': typeof AuthenticatedAdministracaoRoute
  '/apresentacao/$matchId': typeof ApresentacaoMatchIdRoute
  '/relatorio/$matchId': typeof RelatorioMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/administracao'
    | '/apresentacao/$matchId'
    | '/relatorio/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/administracao'
    | '/apresentacao/$matchId'
    | '/relatorio/$matchId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/administracao'
    | '/apresentacao/$matchId'
    | '/relatorio/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApresentacaoMatchIdRoute: typeof ApresentacaoMatchIdRoute
  RelatorioMatchIdRoute: typeof RelatorioMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/administracao': {
      id: '/_authenticated/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AuthenticatedAdministracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/apresentacao/$matchId': {
      id: '/apresentacao/$matchId'
      path: '/apresentacao/$matchId'
      fullPath: '/apresentacao/$matchId'
      preLoaderRoute: typeof ApresentacaoMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio/$matchId': {
      id: '/relatorio/$matchId'
      path: '/relatorio/$matchId'
      fullPath: '/relatorio/$matchId'
      preLoaderRoute: typeof RelatorioMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdministracaoRoute: typeof AuthenticatedAdministracaoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdministracaoRoute: AuthenticatedAdministracaoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApresentacaoMatchIdRoute: ApresentacaoMatchIdRoute,
  RelatorioMatchIdRoute: RelatorioMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
